ONSdigital/address-index-api

server/conf/application.conf

For deploying on Cloud Foundry we can use Environment Labels to specify the parameters used for elastic search with the API.
Tested in ONS Cloud Foundry

Update application.conf to allow use of ENV labels

---

tagger/crftagger/Makefile

Needs to change the makefile to get it to compile for windows.  You @alangorton may want to change the scope of some of the variables.  Checked on Jenkins and builds DLL correctly.

AW patch/crf tagger string

---

demo-ui/app/uk/gov/ons/addressIndex/demoui/views/pager.scala.html
demo-ui/app/uk/gov/ons/addressIndex/demoui/views/singleMatch.scala.html
demo-ui/public/stylesheets/ons.css

Small UI change to make PAF/NAG buttons and matching score coexist on the same row (Taiwo spotted this) and another change to the paging view so that the maximum page number for the next page is correctly processed when it is less than 100.

align PAF/NAG and score, fix page number error

---

parsers/src/main/scala/uk/gov/ons/addressIndex/parsers/Tokens.scala
parsers/src/test/scala/uk/gov/ons/addressIndex/parsers/TokensTest.scala
parsers/src/test/scala/uk/gov/ons/addressIndex/parsers/postTokenizeTreatmentTest.scala

Also fixes a small bug with hyphen treatment where 3A - 3 was transformed into "3A 3" instead of "3A-3"

Removes a feature that transformed a letter from BuildingName into SubBuildingName (as it does not work)

---

server/app/uk/gov/ons/addressIndex/server/utils/Splunk.scala

As we are now going ahead with Splunk, we need the Splunk logging threshold changed from TRACE to INFO. It looks like for Cloud Foundry it has go to STDOUT - otherwise it would have been tidier to write the logs we want in Splunk to a separate physical file.

change splunk logs to info

---

parsers/src/main/scala/uk/gov/ons/addressIndex/parsers/Tokens.scala
server/app/uk/gov/ons/addressIndex/server/utils/HopperScoreHelper.scala
server/test/uk/gov/ons/addressIndex/server/utils/HopperScoreHelperTest.scala

This PR is for the outstanding tasks from PR 177 (which were deferred to not hold up testing). All 37 methods of HopperScoreHelper now have unit tests, and the Tokens code has been tidied up so that fileToList and fileToMap accept pathname parameters (defaulted) and the code to get the  buffered source is not duplicated. Note that the custodian codes will benefit from this change when they are moved to an external file.

Hopper Score: Add missing tests and tidy Tokens file getters

---

model/src/main/scala/uk/gov/ons/addressIndex/model/AddressIndexModel.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala

Example of a request to `/bulk` (with current config parameters in application.conf):
```
{
"addresses": [{
"id": "1",
"address": "132 SOME STREET, EXETER, E10 6GY"
},{
"id": "2",
"address": "132 SOME STREET, EXETER, E10 6GY"
}],
"config":{
"subBuildingName": {
"lpiSaoStartNumberBoost": 1.0,
"lpiSaoStartSuffixBoost": 1.0,
"lpiSaoEndNumberBoost": 1.0,
"lpiSaoEndSuffixBoost": 1.0,
"pafSubBuildingNameBoost": 1.5,
"lpiSaoTextBoost": 1.5
},
"buildingName": {
"lpiPaoStartNumberBoost": 2.5,
"lpiPaoStartSuffixBoost": 3.5,
"lpiPaoEndNumberBoost": 2.5,
"lpiPaoEndSuffixBoost": 2.5,
"pafBuildingNameBoost": 2.5,
"lpiPaoTextBoost": 2.5
},
"buildingNumber": {
"pafBuildingNumberBoost": 2.0,
"lpiPaoStartNumberBoost": 2.0
},
"streetName": {
"pafThoroughfareBoost": 2.0,
"pafWelshThoroughfareBoost": 2.0, …
```

Allows the user of the bulk request to set config parameters manually

---

model/src/main/scala/uk/gov/ons/addressIndex/model/AddressIndexModel.scala
server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/conf/routes

Example of request:
```
{  
"addresses":[  
{  
"id":"1",
"tokens":{  
"PostcodeOut":"EX4",
"BuildingNumber":"1",
"PostcodeIn":"4SW",
"Postcode":"EX4 4SW",
"PaoStartNumber":"1"
}
},
{  
"id":"2",
"tokens":{  
"PostcodeOut":"EX4",
"BuildingNumber":"1",
"PostcodeIn":"4SW",
"Postcode":"EX4 4SW",
"PaoStartNumber":"1"
}
}
],
"config":{  
"subBuildingName":{  
"lpiSaoStartNumberBoost":1.0,
"lpiSaoStartSuffixBoost":1.0,
"lpiSaoEndNumberBoost":1.0,
"lpiSaoEndSuffixBoost":1.0,
"pafSubBuildingNameBoost":1.5,
"lpiSaoTextBoost":1.5
},
"buildingName":{  
"lpiPaoStartNumberBoost":2.5,
"lpiPaoStartSuffixBoost":3.5,
"lpiPaoEndNumberBoost":2.5,
"lpiPaoEndSuffixBoost":2.5,
"pafBuildingNameBoost":2.5,
"lpiPaoTextBoost":2.5
},
"buildingNumber":{  
"pafBuildingNumberBoost":2.0,
"lpiPaoStartNumberBoost":2.0
}, …
```

Adds bulk entrypoint where we can provide tokens instead of input

---

demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/ApplicationHomeController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/app/uk/gov/ons/addressIndex/server/utils/Splunk.scala
server/conf/application.conf

UI calls the login policy on the gateway, then joins the userid and and underscore to the returned apikey.
Gateway policies for API calls split the key to remove the userid before validating the key.
API AddressController gets the api key from the authorization header and splits it to get the userid which is added to the Splunk log.

Log network userid of API requestor to Splunk (JIRA 355)

---

server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/app/uk/gov/ons/addressIndex/server/utils/Splunk.scala

As it now looks like ticket 445 won't be done before we go to master, I have turned off the logging. The security one may get done so I have made a small needed tweak to the API key in anticipation of this being enabled soon.

Disable splunk logging

---

server/app/uk/gov/ons/addressIndex/server/utils/Splunk.scala

The CloudFoundry syslog drain is now working. We don't have an external config way of changing  logging settings currently, so need a very small code change.

Enable splunk logging

---

demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/ApplicationHomeController.scala
demo-ui/conf/application.conf

Old Gateway now working, some small changes required to policy (held in on-site GitLab not public GitHub) and to the  conf and  to  the  home  controller. It  now works, provided the old gateway's IP is specified in Jenkins. New gateway still not quite there.

Changes to application conf and home controller for login

---

demo-ui/test/uk/gov/ons/addressIndex/demoui/client/AddressIndexClientMock.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/AddressResponse.scala
server/app/uk/gov/ons/addressIndex/server/utils/HopperScoreHelper.scala
server/test/uk/gov/ons/addressIndex/server/model/response/AddressResponseAddressSpec.scala
server/test/uk/gov/ons/addressIndex/server/utils/HopperScoreHelperTest.scala

This change exposes the underlying ambiguity penalty on the API response under the bespokescore section.

Add ambiguity penalty to response

---

demo-ui/app/uk/gov/ons/addressIndex/demoui/client/AddressIndexClientInstance.scala
demo-ui/conf/application.conf
model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala

To use the API via the Gateway, its IP needs to be entered in the API URL variable, port 8443 as the API PORT and the new variable ONS_AI_UI_API_GATEWAY_POLICY_PATH needs to be set to the path the policies are expecting for the current environment.

Demo UI config for routing via gateway (JIRA 77)

---

server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala

Retry no longer tests message text which depends on server. Unit tests now include retry parameter for failures.

Make retry work with Netty (or Akka)

---

server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/conf/routes
server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala

Filter and retry params in wrong order on one of the  requests
Sometimes need more that one retry so allow up to 5 (max)

Fix retry issues

---

demo-ui/app/uk/gov/ons/addressIndex/demoui/views/clericalTool.scala.html
demo-ui/conf/application.conf
server/conf/application.conf

This is a small change to set defaults in the config file following  performance testing of the new scoring code. The settings can be overridden in Jenkins. Investigations  (reported on JIRA, Confluence page to follow) showed that we cannot test large numbers of addresses without a significant performance hit, so the minima for the single and bulk are staying quite low. It has also been necessary to reduce the maximum offset to avoid excessive response  size from ES.

Result Fetching Optimisation (JIRA 1000)

---

server/app/uk/gov/ons/addressIndex/server/model/dao/AddressIndexElasticClientProvider.scala

Tested on internal ES - no issue.

Fix for AWS ES. No longer passing in default credentials.

---

server/app/uk/gov/ons/addressIndex/server/utils/HopperScoreHelper.scala
server/test/uk/gov/ons/addressIndex/server/utils/HopperScoreHelperTest.scala

Uses zipwithIndex to fetch previously calculated locality values

Hopper Score efficiency fix

---

demo-ui/app/uk/gov/ons/addressIndex/demoui/utils/RelativesExpander.scala
demo-ui/test/uk/gov/ons/addressIndex/demoui/utils/RelativesExpanderTest.scala
demo-ui/test/uk/gov/ons/addressIndex/demoui/utils/RelativesExpander_NoApplicationTest.scala

Change RelativesExpander class to use formattedAddress as is.

Fix for case of formatted address of hierarchy items

---

server/conf/logback.xml

We are intending to move the routine usage logging from the API (CF) to the Gateway but for now we still need this logging for our Splunk dashboard.

Restore Splunk logging (1497)

---

build.sbt
server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/conf/logback.xml
server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala

Removes nugatory bespoke score calculation from postcode and partial.
build.sbt change for windows runProd also included after testing

Scoring tidy - remove unnecessary calculations

---

server/src/it/resources/uk/gov/ons/gatling/conf/_defaults.conf

Lower the default value for `concurrenUsers` so that an endpoint is not mistakenly overloaded

Change default number of users to 10 from 100

---

README.md
server/src/it/Running Performance Tests.md
server/src/it/macOS Tuning for Gatling.md
server/src/it/resources/uk/gov/ons/gatling/conf/_defaults.conf
server/src/it/scala/uk/gov/ons/gatling/conf/ConfigLoader.scala
server/src/it/scala/uk/gov/ons/gatling/simulations/RegistersSimulation.scala

Renamed numOfConcurrentUsers to numOfRequestsPerSecond since from the
perspective of an end-user, that is what this number represents (From
the point of view of the actual gatling simulation itself, this param is
used for both number of concurrent users as well as concurret requests
per second)
Renamed configName to CONFIG_NAME to align with the other system
properties that the gatling tests accept.

Updated documentation and minor fixes to configuration vars

---

build.sbt
project/plugins.sbt

This change allows the removal of all the 'shell' steps needed after
construction of the zip package via SBT. These manual steps include:
1. Modifying the zip using 'jar uf' to add parser resources (details
below)
2. Creating a copy of the zip to allow using a predicatable name for
the Jenkins Cloud Foundry plugin to push the app bundle.
Removing the need for the shell steps will make this build more portable
and easily reproducible.
Note that this required upgrading sbt-native-packager from v.1.1.4 to
v1.3.3
Before the server (address-index-api/server) can be deployed to Cloud
Foundry, a zip package is created using:
$ sbt "project address-index-server" "universal:packageBin"
and the zip modified by using a command like so:
$ jar uf server/target/universal/address-index-server.zip \
-C …

Override universalBin task for server to include parser resources

---

client/src/test/scala/uk/gov/ons/addressIndex/client/AddressIndexClientTest.scala
demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/ClericalToolController.scala
demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/PostcodeController.scala
demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/RadiusController.scala
demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/SingleMatchController.scala
demo-ui/app/uk/gov/ons/addressIndex/demoui/utils/RelativesExpander.scala
demo-ui/test/uk/gov/ons/addressIndex/demoui/client/AddressIndexClientMock.scala
demo-ui/test/uk/gov/ons/addressIndex/demoui/utils/RelativesExpander_NoApplicationTest.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/AddressIndexModel.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressBySearchResponse.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressResponseAddress.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/partialaddress/AddressByPartialAddressResponse.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/postcode/AddressByPostcodeResponse.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/uprn/AddressByUprnResponse.scala
server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/DebugController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/PartialAddressController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/PostcodeController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/UPRNController.scala
server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
server/app/uk/gov/ons/addressIndex/server/modules/response/PartialAddressControllerResponse.scala
server/app/uk/gov/ons/addressIndex/server/modules/response/PostcodeControllerResponse.scala
server/app/uk/gov/ons/addressIndex/server/modules/response/Response.scala
server/app/uk/gov/ons/addressIndex/server/modules/response/UPRNControllerResponse.scala
server/app/uk/gov/ons/addressIndex/server/utils/HopperScoreHelper.scala
server/conf/routes
server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
server/test/uk/gov/ons/addressIndex/server/model/response/AddressResponseAddressSpec.scala
server/test/uk/gov/ons/addressIndex/server/utils/HopperScoreHelperTest.scala

main single match - verbose flag defaults to true and unwanted data must be discarded after scoring and thresholding
postcode - verbose flag defaults to true (might want to make this false), unwanted data items not gathered
UPRN - verbose flag defaults to true, unwanted data items not gathered
partial - verbose flag defaults to false, unwanted data items not gathered
for consistency partial now uses the same objects as the others rather than its own so the output is slightly different.
The UI has been changed to support verbose settings, and false is used when expanding relatives, everything else uses verbose true.
Unit tests have been updated but what I haven't done is double up everything for a verbose and concise version - will do a separate PR for this if needed and any other changes …

Introduce verbose parameter for all endpoints (1686)

---

client/src/main/scala/uk/gov/ons/addressIndex/client/AddressIndexClient.scala
client/src/test/scala/uk/gov/ons/addressIndex/client/AddressIndexClientTest.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/AddressIndexModel.scala
server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/DebugController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/PostcodeController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/UPRNController.scala
server/conf/routes
server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala

All outputs now default to concise (verbose=false)
Unit tests for both options

Implement Consistent Concise and Verbose output and add tests

---

server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/PartialAddressController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/PostcodeController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/UPRNController.scala
server/app/uk/gov/ons/addressIndex/server/utils/AddressAPILogger.scala

Hides log write out for individual address responses (further work required to convert to trace output).

Update to logging to include verbose, endpoint and activity tags.

---

model/src/main/scala/uk/gov/ons/addressIndex/model/db/index/NationalAddressGazetteerAddress.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressResponseGeo.scala
server/conf/application.conf
server/test/uk/gov/ons/addressIndex/server/model/response/AddressResponseAddressSpec.scala

Change latitude and longitude from Double to BigDecimal to avoid scientific notation in output.
Modify regex in NationalAddressGazetteer case class to deal with scientific notation in location string.
Played with overriding the JSON serialisation but not needed in  the end.

Fix problem with small longitude

---

model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/BatchController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/DebugController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/PartialAddressController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/PostcodeController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/UPRNController.scala
server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexVersionModule.scala
server/app/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepository.scala
server/app/uk/gov/ons/addressIndex/server/utils/AddressAPILogger.scala
server/conf/application.conf
server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala

Each endpoint can now be told which cluster to run on
bulk = ""
bulk = ${?ONS_AI_API_BULK_CLUSTER_NO}
address = ""
address = ${?ONS_AI_API_LIVE_CLUSTER_NO}
If the Environment variables are not set, everything is as before, but if they are set to 1 or 2 the Gateway will direct Elasticsearch requests to a specific cluster. Tested with bulks on 1, others on 2.

Implement Clusterid feature (REG 2016)

---

Jenkinsfile-new
project/plugins.sbt

This commit:
1. Upgrades scalastyle plugin version to the latest 1.0.0
2. Removes scapeGoat static analysis since the reports generated from
it overwrite the ones created by Scalastyle after which neither are
accessible

Fix Static Code Analysis to show ScalaStyle Results

---

Jenkinsfile-new
server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala

The default encoding being picked up by the JVM on jen-m Jenkins was
causing an error while reading a file containing an accented character.
The default encoding for Travis CI builds (and for local execution of
tests) was UTF-8, however for the Jenkins JVM it was not.
Instead of a code change to specify the encoding which might have impact
elsewhere, I chose to specify the encoding only for the specific SBT
task ('test') which obviates the need to evaluate the impact elswhere.
Task: REG-1985

Fix default encoding being used for Jenkins causing a test failure

---

server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala

Change to how the house number boost works. Instead of concatenating all the numbers and doing a single match, it now does separate matches on each number "token".
- Crash no longer occurs
- Gatling test shows same or better speed
- Results almost the same, some small differences which initally look like improvements (should do more testing in Test post-merge).

Fix for ES crash due to too many numbers in partial string (REG 2146)

---

model/src/main/scala/uk/gov/ons/addressIndex/model/db/index/HybridAddress.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/db/index/HybridAddressPartial.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressResponseError.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressResponseStatus.scala
server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/PartialAddressController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/PostcodeController.scala
server/app/uk/gov/ons/addressIndex/server/controllers/UPRNController.scala
server/app/uk/gov/ons/addressIndex/server/modules/response/PartialAddressControllerResponse.scala
server/app/uk/gov/ons/addressIndex/server/modules/response/PostcodeControllerResponse.scala
server/app/uk/gov/ons/addressIndex/server/modules/response/Response.scala
server/conf/application.conf
server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala

When an unexpected error occurs, the circuit breaker still behaves as before, but the error message returned is enhanced so it is clear what the error actually is.

Better deal with 429s (REG-2158)

---

server/app/ErrorHandler.scala

There may be scope for further improvements, this change deals only with the main problem where an HTML "client" error response comes back from Play (and thus from the Gateway) which causes problems for API clients.

Override Play client error handler to give JSON responses (REG 2321)

---

model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
server/app/uk/gov/ons/addressIndex/server/controllers/PartialAddressController.scala
server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
server/conf/application.conf
server/conf/routes
server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala

After looking at options to do it in the search query (such as creating a plugin) I ended up doing the boosting in the API code. If the full address starts with the search text, a boost of 0+ points is added to the elastic score. For test purposes this is a query string parameter with a configurable default (currently 2). The query string parameter can be removed once a good setting is determined.
Tests were also done on limiting the fields searched, but there was no obvious big performance hit and we do want to keep the accuracy of checking all versions of the address.

Implement startboost function on partial (REG-1823)

---

server/app/uk/gov/ons/addressIndex/server/controllers/RandomController.scala
server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
server/app/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepository.scala
server/conf/application.conf
server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala

verbose = false runs on skinny
cluster id can be explicitly set in Jenkins or allowed to default to the bulk setting.

Enable Skinny index for Random and make cluster customisable (REG-2363)

---

server/src/it/resources/uk/gov/ons/gatling/conf/_defaults.conf
server/src/it/scala/uk/gov/ons/gatling/simulations/RegistersTypeaheadRandomSimulation.scala

The new test gets a random address from the cluster that partials are not run on, then constructs a series of partial queries using this address starting from 5 characters and going up to 20, but stopping when the correct URPN is in the top 4 results.
The code does contain a bit of repetition (problem with .foreach that may or may not be fixable) and I haven't tried to remove the randoms from the headline chart (need to go to the detailed report to get the mean response for partials) or capture the stats for the numbers of characters required to match each address (though these can be viewed in the Jenkins console log).

New gatling simulation for random partial addresses (REG-2358)

---

server/conf/application.conf

on-prem testing shows this is the best setting (auto / 2 is too slow)

set fuzziness to 1

---

api-definitions/ai-swagger.json
api-definitions/explore-the-api/rh/uprn/readme.md
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressResponseAddressUPRNRH.scala
model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/rh/AddressByRHUprnResponse.scala
server/test/uk/gov/ons/addressIndex/server/model/response/AddressResponseAddressSpec.scala

Returns the organisation name from the PAF or NAG record according to preference order.
Does not require an index change because UPRN always runs on the fat index on GCP.

Add organisation name to RH UPRN output

---

server/conf/application.conf

ONS_AI_API_SCALE_FACTOR is for singles and we lowered this for CC (aux results)
ONS_AI_API_BULK_SCALE_FACTOR is the bulk setting and this is set to 23 
Whilst the JIRA ticket to tune the scale factor(s) is still outstanding, a figure of 21 has been working well on the single matches (mainly via UI) on-prem so we want to restore this to the default for GCP deployments.

Change single match scale factor to match on-prem

---

model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
server/conf/application.conf
server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala

The extra boost is just enough to nudge the addressBasePostal=N addresses down the list, except where they really are a better match. Note that this does seem to fix the property shell issue noted in the recent NLP testing.
I have also removed NISRA fields from the queries (breaking a lot of tests) but the aux ones (tokens.xxxx) are still there.

Boost scores of addresses that can receive post 
