- tagger/crftagger/Makefile
Previous made a mistake in updating the wrong branch with windows DLL build - needs to be set to SO.
> Revert erroneous changes made to Linux build

- tagger/crftagger/Makefile
Added default JVM include path location to makefile to be compatible with Centos JDK
> Addition of include path for compile

- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/singleMatch.scala.html
- demo-ui/public/stylesheets/ons.css
Moving the divs made the toggle stop working so had to change javascript. 
Taiwo asked for border to be removed from paging box
> fix paf nag toggle and remove border from page box

- model/src/main/scala/uk/gov/ons/addressIndex/model/AddressIndexModel.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
- model/src/test/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfigTest.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/conf/application.conf
> bulk upload to return failures

- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
It will help us not spam the ES instance with thousands of requests at the same time)
> Makes the call to the ES blocking (we need to wait for the previous bulk to finish before starting the new ons)

- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/clericalTool.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/singleMatch.scala.html
Small fix for Al's W3C report (remove unwanted id= s)
> fix w3c problems with ids

- server/conf/application.conf
> Changing the defaults

- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/app/uk/gov/ons/addressIndex/server/utils/Splunk.scala
- server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala
Also modifies tests so that changing boost wont fail tests
Also puts splunk logs on trace (as no splunk instance is currently used)
> Upadtes query (requested by Sami)

- demo-ui/conf/application.conf
- model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/conf/application.conf
- server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala
ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-dis-max-query.html
> Uses dis_max instead of `should`

- model/src/main/scala/uk/gov/ons/addressIndex/model/db/index/PostcodeAddressFileAddress.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/AddressResponse.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
- server/test/uk/gov/ons/addressIndex/server/model/response/AddressResponseAddressSpec.scala
- server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala
we expected it to be spelled as organization name
> Fixes the problem where organisation name wasn't fetched from ES because

- client/src/main/scala/uk/gov/ons/addressIndex/client/AddressIndexClient.scala
- demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/BulkMatchController.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/AddressIndexModel.scala
Hotfix to make bulk work  again
> Fix problem with bulk body and apikey

- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/conf/application.conf
- server/conf/routes
Defaults to the parameter from the config.
> Gives a possibility to provide `limitPerAddress` for a bulk upload from url.

- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/help.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/helpcy.scala.html
This needs to be merged and pushed to master before the query changes
> Changes to multiple match wording

- demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/ApplicationHomeController.scala
- demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/ClericalToolController.scala
- demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/SingleMatchController.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/app/uk/gov/ons/addressIndex/server/utils/HopperScoreHelper.scala
- server/app/uk/gov/ons/addressIndex/server/utils/Splunk.scala
Review of what is logged (see confluence notes) shows we are logging too much.  More sophisticated control is desirable but this is a quick change to make the numbers more manageable
> Quick change to reduce volume of logging

- model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/app/uk/gov/ons/addressIndex/server/utils/Splunk.scala
- server/conf/application.conf
- server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala
May be merged or deleted according to results of testing
> Shingles Query (no nesting, old synonyms)

- server/app/uk/gov/ons/addressIndex/server/utils/HopperScoreHelper.scala
- server/test/uk/gov/ons/addressIndex/server/utils/HopperScoreHelperTest.scala
Fix nag building score and update test
> Fix for bug where 16 and 16A get the same score

- server/app/uk/gov/ons/addressIndex/server/utils/HopperScoreHelper.scala
- server/test/uk/gov/ons/addressIndex/server/utils/HopperScoreHelperTest.scala
This fixes the matching  logic, but doesn't address the Inverse Term Frequency issue (for later)
> Hopper Score #5 (JIRA 538)

- server/app/uk/gov/ons/addressIndex/server/utils/HopperScoreHelper.scala
- server/test/uk/gov/ons/addressIndex/server/utils/HopperScoreHelperTest.scala
This fixes one of the problems found by Karen
> Hopper score fix for building number - JIRA 600

- model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/conf/application.conf
- server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala
Includes changes from paosao605 branch
> Combined PAO SAO and Query Parameters changes

- parsers/src/main/scala/uk/gov/ons/addressIndex/parsers/Tokens.scala
- parsers/src/test/scala/uk/gov/ons/addressIndex/parsers/PostCodeValidationTest.scala
Small change to Tokens.scala and add new test
> fix problem with duplicate postcode part (JIRA 611)

- server/app/uk/gov/ons/addressIndex/server/utils/HopperScoreHelper.scala
- server/test/uk/gov/ons/addressIndex/server/utils/HopperScoreHelperTest.scala
Small change to logic and two new tests
> Correct building number Hopper score for number only (JIRA 612)

- model/src/main/scala/uk/gov/ons/addressIndex/model/db/index/HybridAddress.scala
Test UPRN 10003321921 - internal branch with change, internal dev without
> Add sort to relatives map - JIRA 610

- model/src/main/scala/uk/gov/ons/addressIndex/model/db/index/Relative.scala
Probably could be done with less code, but this does the trick.
> Fix to deal with Integer uprns

- build.sbt
- demo-ui/conf/application.conf
- project/plugins.sbt
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/conf/application.conf
Clean branch.  I have left in the Netty / Akka toggle (will test singles later)
> Config changes for play timeouts

- model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/AddressResponse.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexCannedResponse.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/conf/application.conf
This will enable us to specify which API deployments must be routed through the Gateway
> Implement optional source key (for JIRA 97)

- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/DebugController.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/conf/routes
- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
- server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala
> Add filter options to address-index-server

- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/addressPartial.scala.html
- model/src/main/scala/uk/gov/ons/addressIndex/model/db/index/NationalAddressGazetteerAddress.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/conf/routes
Add dummy calls for lists (these are served from the Gateway) to API inc swagger desc
Fix error in custodian list inAPI
Reinstate anchor on clerical page on  UI
> API changes for REG 693 (list helpers) plus two small bugs 701 and 705

- demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/ClericalToolController.scala
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/addressPartial.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/clericalTool.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/clericalToolAddresses.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/main.scala.html
Uses gateway path and allocated api key after login
> Changes to Demo UI to make hierarchy work through gateway (REG674)

- build.sbt
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/AddressResponse.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexCannedResponse.scala
- server/conf/routes
- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
No longer required thanks to heartbeat
> Remove retry mechanism

- demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/SingleMatchController.scala
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/result.scala.html
- demo-ui/conf/application.conf
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
API: Bug fix for no space in postcode
> UI: Bug fix for apikey in postcode hierarchy

- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/AddressResponse.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexCannedResponse.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
Includes tests that the point is within the maximum lat (60.9) and minimum lat (49.8) and also maximum lon (1.8) and minimum lon (-8.6)
> Improve validation and tests for radius in API

- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/AddressResponse.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/conf/routes
Add conf score to bulk, change calculation, temp fix for paging
> Fix for new score in API

- demo-ui/test/uk/gov/ons/addressIndex/demoui/client/AddressIndexClientMock.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/AddressResponse.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexCannedResponse.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/conf/application.conf
- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
Jenkins variables 20 for single, 5 for bulk
> Make scoring sample size configurable

- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/forms/singleAddressForm.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/pager.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/singleMatch.scala.html
- demo-ui/conf/messages.cy
- demo-ui/conf/messages.en
Update exact match limiter to add 0
Fixed paging bug of more pages than results
> Update total results message

- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/conf/routes
- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
Seems it  got lost in the wash :-0
> Reinstate bulk-full feature

- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/devcontent/devTypeAhead.scala.html
Updates typeahead demo page to use new partial end point
> Resolves REG-1360

- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/devcontent/devUprn.scala.html
> Small fix for developer page

- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/devcontent/devLanding.scala.html
- demo-ui/conf/application.conf
- model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
Small change to make  swagger links work from AWS or locally.
> Fix off-network swagger (1674)

- runGatlingBulk.sh
- runGatlingBulkFull.sh
- runGatlingBulkLocal.sh
- server/src/it/resources/gatling.conf
- server/src/it/resources/uk/gov/ons/gatling/conf/_application.conf
- server/src/it/resources/uk/gov/ons/gatling/conf/_defaults.conf
- server/src/it/resources/uk/gov/ons/gatling/conf/ai-api-bulk-full-1k.json
- server/src/it/resources/uk/gov/ons/gatling/conf/ai-api-bulk-full-2.5k.json
- server/src/it/resources/uk/gov/ons/gatling/conf/ai-api-bulk-full-2k.json
- server/src/it/resources/uk/gov/ons/gatling/conf/ai-api-bulk-local.json
- server/src/it/resources/uk/gov/ons/gatling/conf/ai-api-bulk.conf
- server/src/it/scala/uk/gov/ons/gatling/conf/ConfigLoader.scala
- server/src/it/scala/uk/gov/ons/gatling/simulations/RegistersSimulationClosedModel.scala
- server/src/it/scala/uk/gov/ons/gatling/simulations/RegistersSimulationOpenModel.scala
Note that there are no changes to the scala code. The only changes
required were to add additional configuration to support the bulk
endpoint (for instance the json payload for POST request)
> Create configuration and shell scripts for executing /bulk Gatling tests

- server/src/it/resources/data/typeahead.csv
- server/src/it/resources/data/typeahead2.csv
- server/src/it/scala/uk/gov/ons/gatling/simulations/RegistersTypeaheadResultsCustomSimulation.scala
Similar to the previous typeahead one, but it checks the results to see when the correct UPRN makes it into the top four. Initially to test REG-2146 but should be re-usable
> New Gatling test for results

- model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/PartialAddressController.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/app/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepository.scala
- server/conf/application.conf
- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
New config / env variables for skinny index alias.
AddressIndexRepository now uses skinny index for partials if verbose=false
> Plumb in Skinny Index to API (REG-2289)

- README.md
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/src/it/Running Performance Tests.md
> Update address-index-api readme (REG 2324)

- api-definitions/ai-swagger.json
- server/app/ErrorHandler.scala
- server/conf/routes
Just routes and swagger (+small improvement to error handler)
> Remove deprecated calls from API (REG-2436)

- model/src/main/scala/uk/gov/ons/addressIndex/model/db/index/HybridAddress.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/db/index/HybridAddressSkinny.scala
- server/app/uk/gov/ons/addressIndex/server/utils/HopperScoreHelper.scala
> Fix capitalisation issue with Hopper Score

- server/app/uk/gov/ons/addressIndex/server/controllers/AddressController.scala
- server/app/uk/gov/ons/addressIndex/server/modules/SystemBootstrap.scala
Also includes change from PR 458
> Fix for CRF tagger 

- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressResponseAddress.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/partialaddress/AddressResponsePartialAddress.scala
- server/test/uk/gov/ons/addressIndex/server/model/response/AddressResponseAddressSpec.scala
Removed one un-used duplicate of a function
Updated the same function to only consider NAG addresses that match perfectly on language
Minor non-functional refactors
Corrected one test to match the altered expectations
> Blank Welsh NAG if no Welsh NAG exists

- .travis.yml
- build.sbt
In addition to the docker to GCP, do a normal publish to artifactory
> New build part IV - artifactory (FWMT-1182)

- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala
Changes made to structure of "full match" query with Iva
Results already tested (further tickets for small improvements raised)
Once merged to develop will need another merge to active NISRA branch
> Query code cleanup 1232

- model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/conf/application.conf
- server/test/uk/gov/ons/addressIndex/server/modules/ElasticsearchRepositorySpec.scala
Works OK except some issues with partial "all" (equal playing fields) where some further investigation is needed into scoring oddities.
> NISRA set boosts and make them configurable

- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
Required for completion of FWMT-1386, universal bin packaging.
Also makes all the tests pass consistently again. Hopefully.
> Brute-force reset the circuit breaker after every test.

- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
make radiusquery a double should
> Fix for NI radius

- demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/ClericalToolController.scala
- demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/SingleMatchController.scala
- demo-ui/app/uk/gov/ons/addressIndex/demoui/model/SingleSearchForm.scala
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/addressShortForm.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/clericalTool.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/clericalToolAddresses.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/forms/singleAddressForm.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/pager.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/postcodeMatch.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/radiusMatch.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/singleMatch.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/singleSearch.scala.html
- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/uprnResult.scala.html
- demo-ui/conf/application.conf
- demo-ui/conf/routes
- demo-ui/test/uk/gov/ons/addressIndex/demoui/controllers/ClericalToolNoAppTest.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/config/AddressIndexConfig.scala
Allows niboost flag to be set for single matches and clericals (FWMT-1517)
> Change to UI to assist with NISRA testing

- demo-ui/app/uk/gov/ons/addressIndex/demoui/views/addressResult.scala.html
- demo-ui/conf/messages.cy
- demo-ui/conf/messages.en
additional change for FWMT-1517
> add nisra fields to uprn

- demo-ui/app/uk/gov/ons/addressIndex/demoui/controllers/BulkMatchController.scala
deal with all header options in minibulk
> Hotfix for UI

- server/app/uk/gov/ons/addressIndex/server/utils/ConfidenceScoreHelper.scala
- server/test/uk/gov/ons/addressIndex/server/utils/ConfidenceScoreHelperTest.scala
- server/test/uk/gov/ons/addressIndex/server/utils/HopperScoreHelperTest.scala
15 -> 23 to correct sigmoid curve
> Small change to confidence score algorithm

- README.md
- docker-compose.yml
Last two commits had wrong summary - ignore. URL's updated to use master and ES version added to readme.
> Fwmt 2097 docker images

- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressResponseAddressPostcodeEQ.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressResponseAddressPostcodeRH.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/eq/AddressByEQUprnResponse.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/rh/AddressByRHUprnResponse.scala
- server/test/uk/gov/ons/addressIndex/server/model/response/AddressResponseAddressSpec.scala
> Bugfixes for NISRA data and EQ / RH Endpoints

- api-definitions/ai-swagger.json
- api-definitions/explore-the-api/eq/bucket/readme.md
- api-definitions/explore-the-api/eq/readme.md
- api-definitions/explore-the-api/groupedpostcode/readme.md
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressResponseAddressBucketEQ.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/address/AddressResponseError.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/eq/AddressByEQBucketResponse.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/eq/AddressByEQBucketResponseContainer.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/EQBucketController.scala
- server/app/uk/gov/ons/addressIndex/server/model/dao/QueryValues.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/app/uk/gov/ons/addressIndex/server/modules/QueryArgs.scala
- server/app/uk/gov/ons/addressIndex/server/modules/response/PostcodeControllerResponse.scala
- server/app/uk/gov/ons/addressIndex/server/modules/validation/PostcodeControllerValidation.scala
- server/conf/routes
- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
> Add new special bucketed postcode endpoint for eq

- api-definitions/ai-openapi.json
- api-definitions/ai-swagger.json
- api-definitions/explore-the-api/addresses/readme.md
- api-definitions/explore-the-api/partial/readme.md
- api-definitions/explore-the-api/postcode/readme.md
- api-definitions/explore-the-api/uprn/readme.md
- api-definitions/readme.md
The file was generated using the iheart play swagger plugin using a branch that cannot be merged yet due to sbt issues. It is valid according to swagger.io editor.
> Add openapi definition

- api-definitions/ai-swagger.json
- api-definitions/explore-the-api/eq/readme.md
- server/app/uk/gov/ons/addressIndex/server/controllers/EQController.scala
- server/conf/routes
- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
May make this more intelligent in future - e.g. group if more than one bucket, or group if more than x results.
> Add flag to eq endpoint for grouping full postcodes

- api-definitions/explore-the-api/eq/readme.md
- model/src/main/scala/uk/gov/ons/addressIndex/model/db/index/HybridAddressCollection.scala
- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/eq/AddressByEQPostcodeResponse.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/EQController.scala
- server/app/uk/gov/ons/addressIndex/server/controllers/EQPostcodeController.scala
- server/app/uk/gov/ons/addressIndex/server/model/dao/QueryValues.scala
- server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala
- server/app/uk/gov/ons/addressIndex/server/modules/QueryArgs.scala
- server/app/uk/gov/ons/addressIndex/server/utils/ValueObjects.scala
- server/src/it/scala/uk/gov/ons/gatling/simulations/RegistersEQCustomSimulation.scala
- server/test/uk/gov/ons/addressIndex/server/controllers/AddressControllerSpec.scala
Combined query is slower than the normal postcode one but much quicker than doing two. Very flexible for EQ and hopefully the performance hit will be acceptable.
> New Combo option for postcodes

- demo-ui/public/pages/radiustest.html
update leaflet details to replace expired tiles
> Fix map demo tiles

- build.sbt
- project/build.properties
- project/plugins.sbt
- server/app/uk/gov/ons/addressIndex/server/controllers/SwaggerController.scala
- server/conf/application.conf
- server/conf/routes
- server/conf/swagger-custom-mappings.yml
- server/conf/swagger.yml
- version.sbt
Swagger upgraded to V3 and on-demand class added.
> Update sbt in API project to newest that works with play 2.6

- build.sbt
- server/app/uk/gov/ons/addressIndex/server/modules/SystemBootstrap.scala
Test build deployed on initial-test-3
> JDK Version change to avoid CRF load error

- server/app/uk/gov/ons/addressIndex/server/controllers/SwaggerController.scala
- server/conf/application.conf
> remove host from swagger output

- model/src/main/scala/uk/gov/ons/addressIndex/model/server/response/bulk/AddressBulkResponseAddress.scala
- server/test/uk/gov/ons/addressIndex/server/model/response/AddressBulkResponseAddressSpec.scala
- server/test/uk/gov/ons/addressIndex/server/model/response/AddressResponseAddressSpec.scala
- version.sbt
New bulk response unit test added
> Add Parent uprn and udprn to bulk response
